apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails-ops-web
  labels:
    app: rails-ops-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rails-ops-web
  template:
    metadata:
      labels:
        app: rails-ops-web
    spec:
      containers:
      - name: rails-ops-web
        image: rails-ops:latest
        ports:
        - containerPort: 3000
        env:
        - name: RAILS_ENV
          value: "production"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: rails-ops-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: rails-ops-secrets
              key: redis-url
        - name: ELASTICSEARCH_URL
          valueFrom:
            secretKeyRef:
              name: rails-ops-secrets
              key: elasticsearch-url
        - name: RAILS_MASTER_KEY
          valueFrom:
            secretKeyRef:
              name: rails-ops-secrets
              key: rails-master-key
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: rails-ops-secrets
              key: secret-key-base
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /up
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /up
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: rails-ops-web-service
spec:
  selector:
    app: rails-ops-web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer
